FROM zt1115798334/centos7.9.2009-jdk8u332
RUN set -eux; 	yum -y update
RUN set -eux; \
 	yum  -y install \
 	 	make \
        gcc \
        zip \
        gcc-c++ \
        git ; \
    rm -rf /var/cache/yum \





