version: '2'
services:
  mysql-nacos:
    container_name: mysql-nacos
    image: nacos/nacos-mysql:8.0.16
    env_file:
      - ./mysql-nacos/env/mysql-nacos.env
    volumes:
      - ./mysql-nacos/db:/var/lib/mysql
    ports:
      - "3308:3306"
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
    restart: always
  nacos:
    image: nacos/nacos-server
    container_name: nacos
    env_file:
      - ./nacos/env/nacos.env
    volumes:
      - ./nacos/logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9555:9555"
    depends_on:
      - mysql-nacos
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
    restart: always