version: '2.0'
services:
  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"
    volumes:
#      - ./data-master/rabbitmq:/var/lib/rabbitmq
#      - /etc/localtime:/etc/localtime
      - ./config/rabbitmq.conf:/etc/rabbitmq/conf.d/rabbitmq.conf
      - ./cookie/erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
    restart: always